### ISSUE TITLE
The `User` instance is not valid

### ISSUE THREAD

**Issue by kitvv** [qxl1231/generator-loopback-vue#3]
你好，我把数据库改成了mysql，然后添加管理员的时候遇到以下问题。
 
CMD ：`node server/bin/create-admin.js`
> /xxxxxxx/generator-loopback-vue/node_modules/mysql/lib/protocol/Parser.js:78
>         throw err; // Rethrow non-MySQL errors
>         ^
> ValidationError: The `User` instance is not valid. Details: `username` is invalid (value: "test").

**Comment by qxl1231** [comment]
你如果使用的mysql,需要修改好几个地方:
1.datasources.json 
```    
"appversion": {
    "host": "localhost",
    "port": 27017,
    "database": "temp_db",
    "name": "appversion",

    "connector": "mongodb"  --- 改成mysql
  }
  ```

2.增加npm i loopback-connector-mysql 到package.json中
3.把model-config.json 中的 "dataSource": "appversion" 确保对应的是mysql数据库实例

从你的问题来看,你肯定没有仔细看过lb的官方文档,建议先看文档再做比较好一点

**Comment by kitvv** [comment]
你好，谢谢回复
我这三点都做了，才出的问题。
之前我怀疑User是mysql的保留字，但貌似也不是。

**Comment by qxl1231** [comment]
你得把你修改的,和报错信息再研究下,实在不行就用nosql的mongodb把,ValidationError: The User instance is not valid. Details: username is invalid (value: "test"). 这句话更像是在说值非法或者 数据库的字段不可用
