### ISSUE TITLE
会支持 Vue 2.0 吗？

### ISSUE THREAD

**Issue by crazcdll** [qxl1231/generator-loopback-vue#4]
作者打算支持 Vue 2.0 吗？毕竟 2.0 的改变还是蛮大的，期待！

**Comment by qxl1231** [comment]
理论上你把依赖的packege里的vue 改成2.0.x就可以了,但是不确定的是vue-resouce和vue-route是否支持2.0

**Comment by crazcdll** [comment]
Vue 2.0 已经把推荐的换成 Vue-axios 了，Vue-Route 的话，官方出了 Vue-Router，所以是不是理论上是可以的

**Comment by qxl1231** [comment]
可以的.,你把这2个依赖换成你说的,试一下,应该没问题,这里面只用到了基础的东西
